### ISSUE TITLE
feat: send to Readwise with the URL of the Roam Research block?

### ISSUE THREAD

**Issue by JimmyLv** [mlava/roam-send-readwise#2]
Hey Mark, this plugin is so cool, thanks for the contribution!

When sending to Readwise, is it possible to append a block backlink to Roam Research?

e.g. https://roamresearch.com/#/app/Note-Tasking/page/1nKfnjsW7

![Google Chrome-Notes from Roam Research  Readwise-001029-20221125](https://user-images.githubusercontent.com/4997466/203980257-7948ea37-aee2-46b1-a22c-d9c62af2011b.png)

**Comment by mlava** [comment]
Hi Jimmy, 
Sorry, I got snowed under and forgot about this for a bit.
This is now implemented and awaiting review in the Roam Depot github.
Thanks for the good suggestion!
