### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by tombarys** [mlava/roam-send-readwise#4]
Hi, Mark, I have problem using the plugin. It does not work at all, console returns "Error: 400". I had the same problem with my own cljs Readwise plugin and two things helped: I both replaced URL backlinking using "Roam desktop links" to standard full URLs (strange) and finally: I removed sending empty note (`""`) when there was no note at all. Now my plugin works again, but your plugin does not work. Thanks!

**Comment by mlava** [comment]
Thanks for reporting. I will look, but thought I already had logic in there to handle empty strings. Will check and return. Cheers!

**Comment by mlava** [comment]
@tombarys 
I can't reproduce this at all. I've tried all the various settings and it appears to work fine. I have no console errors.
Is this resolved for you??

**Comment by tombarys** [comment]
Hi, it does not work for me... this is the console error message: `>POST https://readwise.io/api/v2/highlights/ 400`.

**Comment by mlava** [comment]
Hey Tomáš,
I know this might be a silly question, but could you confirm you've got the
correct API key from https://readwise.io/access_token in your RR settings?
Cheers,
Mark

**Comment by tombarys** [comment]
It is not silly, I understand well! Generated, copy-pasted again, you can see below. Even changed the name of the "book" to different to create a new one, but still the same error. What next to check?

![CleanShot 2023-05-19 at 14 34 36@2x](https://github.com/mlava/send-readwise/assets/5729352/70c83f86-37da-4af0-b4b6-8c2d5c884355)
![CleanShot 2023-05-19 at 14 36 07@2x](https://github.com/mlava/send-readwise/assets/5729352/bafb2b3d-1970-478e-ae82-0c4bd898598b)

**Comment by mlava** [comment]
Thanks for your feedback here and on Twitter.
PR submitted. https://github.com/Roam-Research/roam-depot/pull/682
